from datetime import datetime
import json
from src.config import working_dir

def timestampToDate(timestamp):
    dateobj = datetime.fromtimestamp(timestamp)
    # print("[timestampToDate]: ", dateobj.strftime("%Y-%m-%d %H:%M:%S"))
    return dateobj.strftime("%Y-%m-%d %H:%M:%S")

class HTMLEmail:
    def __init__(self, title, desc="", vlist=None) -> None:
        # html renderred by title, desc, date, content, in which 
        # content is generated by self.vContents()
        # css style
        self.css_template = """\
        <!DOCTYPE html>
            <html lang="en" xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml"
            xmlns:o="urn:schemas-microsoft-com:office:office">

            <head>
            <title> Garton's notification </title>
            <meta http-equiv="X-UA-Compatible" content="IE=edge" />
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <style type="text/css">
                #outlook a {
                padding: 0;
                }

                body {
                margin: 0;
                padding: 0;
                -webkit-text-size-adjust: 100%;
                -ms-text-size-adjust: 100%;
                }

                table,
                td {
                border-collapse: collapse;
                mso-table-lspace: 0pt;
                mso-table-rspace: 0pt;
                }

                img {
                border: 0;
                height: auto;
                line-height: 100%;
                outline: none;
                text-decoration: none;
                -ms-interpolation-mode: bicubic;
                }

                p {
                display: block;
                margin: 13px 0;
                }
            </style>
            <link href="https://fonts.googleapis.com/css?family=Nunito:100,400,700" rel="stylesheet" type="text/css" />
            <style type="text/css">
                @import url(https://fonts.googleapis.com/css?family=Nunito:100,400,700);
            </style>
            <style type="text/css">
                @media only screen and (min-width:480px) {
                .mj-column-per-100 {
                    width: 100% !important;
                    max-width: 100%;
                }

                .mj-column-per-50 {
                    width: 50% !important;
                    max-width: 50%;
                }

                .mj-column-per-30 {
                    width: 30% !important;
                    max-width: 30%;
                }

                .mj-column-per-70 {
                    width: 70% !important;
                    max-width: 70%;
                }
                }
            </style>
            <style type="text/css">
                @media only screen and (max-width:480px) {
                table.mj-full-width-mobile {
                    width: 100% !important;
                }

                td.mj-full-width-mobile {
                    width: auto !important;
                }
                }
            </style>
            <style type="text/css">
                a,
                span,
                td,
                th {
                -webkit-font-smoothing: antialiased !important;
                -moz-osx-font-smoothing: grayscale !important;
                }
            </style>
            </head>
        """
        # html: title, date, desc, contents (from video_template)
        self.html_template = """\
            <body style="background-color:#eaeaea;">
            <div
                style="display:none;font-size:1px;color:#ffffff;line-height:1px;max-height:0px;max-width:0px;opacity:0;overflow:hidden;">
                Preview - Welcome to Garton's Mails </div>
                <div style="background-color:#eaeaea;"></div>
                <div style="margin:0px auto;max-width:600px;">
                <table align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="width:100%;">
                    <tbody>
                    <tr>
                        <td style="direction:ltr;font-size:0px;padding:20px 0;text-align:center;">
                        <div class="mj-column-per-100 mj-outlook-group-fix"
                            style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;">
                            <table border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;"
                            width="100%">
                            <tbody>
                                <tr>
                                <td style="font-size:0px;word-break:break-word;">
                                    <div style="height:20px;">   </div>
                                </td>
                                </tr>
                            </tbody>
                            </table>
                        </div>
                        </td>
                    </tr>
                    </tbody>
                </table>
                </div>


                <div style="background:#ffffff;background-color:#ffffff;margin:0px auto;max-width:600px;">
                <table align="center" border="0" cellpadding="0" cellspacing="0" role="presentation"
                    style="background:#ffffff;background-color:#ffffff;width:100%;">

                    <tbody>
                    <tr>
                        <td style="direction:ltr;font-size:0px;padding:0px;text-align:center;">

                        <!-- date title desc -->
                        <div style="margin:0px auto;max-width:600px;">
                            <table align="center" border="0" cellpadding="0" cellspacing="0" role="presentation"
                            style="width:100%;">
                            <tbody>
                                <tr>
                                <td style="direction:ltr;font-size:0px;padding:20px 0;text-align:center;">
                                    <div class="mj-column-per-100 mj-outlook-group-fix"
                                    style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;">
                                    <table border="0" cellpadding="0" cellspacing="0" role="presentation"
                                        style="vertical-align:top;" width="100%">
                                        <tbody>
                                        <tr>
                                            <td align="left" style="font-size:0px;padding:10px 25px;word-break:break-word;">
                                            <div
                                                style="font-family:Nunito, Helvetica, Arial, sans-serif;font-size:16px;font-weight:bold;line-height:20px;text-align:left;color:#54595f;">
                                                <h2
                                                style="margin: 0; font-size: 24px; line-height: 32px; line-height: normal; font-weight: bold;">
                                                {title}</h2>
                                                <p class="date"
                                                style="margin: 0 0 5px 0; margin-bottom: 5px; font-size: 16px; font-weight: normal;">
                                                {date}</p>
                                            </div>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td align="left" style="font-size:0px;padding:10px 25px;word-break:break-word;">
                                            <div
                                                style="font-family:Nunito, Helvetica, Arial, sans-serif;font-size:16px;font-weight:400;line-height:20px;text-align:left;color:#54595f;">
                                                <p style="margin: 0 0 5px 0;">{desc}</p>
                                            </div>
                                            </td>
                                        </tr>
                                        </tbody>
                                    </table>
                                    </div>
                                </td>
                                </tr>
                            </tbody>
                            </table>
                        </div>
                        {contents}                  
                    </tbody>
                </table>
                </div>
                </div>
            </body>
            </html> 
        """      
        self.video_template = """\
                <!-- img video_date video_title -->
                <div style="background:{background};background-color:{background};margin:0px auto;max-width:600px;">
                    <table align="center" border="0" cellpadding="0" cellspacing="0" role="presentation"
                    style="background:{background};background-color:{background};width:100%;">
                    <tbody>
                        <tr>
                        <td style="direction:ltr;font-size:0px;padding:20px 0;text-align:center;">
                            <div class="mj-column-per-30 mj-outlook-group-fix"
                            style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:middle;width:100%;">
                            <table border="0" cellpadding="0" cellspacing="0" role="presentation"
                                style="vertical-align:middle;" width="100%">
                                <tbody>
                                <tr>
                                    <td align="center" style="font-size:0px;padding:10px 25px;word-break:break-word;">
                                    <table border="0" cellpadding="0" cellspacing="0" role="presentation"
                                        style="border-collapse:collapse;border-spacing:0px;" class="mj-full-width-mobile">
                                        <tbody>
                                        <tr>
                                            <td style="width:130px;" class="mj-full-width-mobile">
                                            <img height="auto" src="{pic}" alt="Image does not show"
                                                style="border:0;display:block;outline:none;text-decoration:none;height:auto;width:100%;font-size:16px;"
                                                width="130" />
                                            </td>
                                        </tr>
                                        </tbody>
                                    </table>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                            </div>
                            <div class="mj-column-per-70 mj-outlook-group-fix"
                            style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:middle;width:100%;">
                            <table border="0" cellpadding="0" cellspacing="0" role="presentation"
                                style="vertical-align:middle;" width="100%">
                                <tbody>
                                <tr>
                                    <td align="left" style="font-size:0px;padding:10px 25px;word-break:break-word;">
                                        <div style="font-family:Nunito, Helvetica, Arial, sans-serif;font-size:16px;font-weight:400;line-height:20px;text-align:left;color:#54595f;">
                                            <h3><a href="{url}"
                                                style="color: #54595f; text-decoration: underline;">{video_title}</a></h3>
                                            <p class="date"
                                                style="margin: 0 0 5px 0; margin-bottom: 5px; font-size: 16px; font-weight: normal;">
                                                {video_date}</p>
                                            <p class="date"
                                                style="margin: 0 0 5px 0; margin-bottom: 5px; font-size: 16px; font-weight: normal;">
                                                时长:{length}; {play}次播放;</p>
                                        </div>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                            </div>
                        </td>
                        </tr>
                    </tbody>
                    </table>
                </div>
                </td>
            </tr>
        """
        self.contents = ""
        self.html = ""
        self.vlist = vlist
        self.date = datetime.now().timestamp()
        self.title = title
        self.desc = desc

    def updateVlist(self, vlist):
        self.vlist = vlist

    def vContent(self, background, url, pic, title, timestamp, length, play):
        return self.video_template.format(
                                    background=background,
                                    url=url,
                                    pic=pic,
                                    video_title=title,
                                    video_date=timestampToDate(timestamp),
                                    length=length,
                                    play=play
                                )
    
    def vContents(self):
        for i, each in enumerate(self.vlist):
            background = "#ffffff" if i % 2 else "#f8f8f8"
            content = self.vContent(
                background,
                "https://www.bilibili.com/video/"+each['bvid'],  # url
                each['pic'],
                each['title'],
                each['created'],  # convert to date in vContent()
                each['length'],
                each['play']
            )
            self.contents += content
        return self.contents
            
    def generate(self):
        contents = self.vContents()
        html = self.html_template.format(
                                    date=timestampToDate(self.date),
                                    title=self.title,
                                    desc=self.desc,
                                    contents=contents
                                )
        self.html = self.css_template + html
        return self.html
    
def main():
    # str = timestampToDate(datetime.now().timestamp())
    # print(str)

    jsonData = None
    with open("./tmp.json", "r") as f:
        data = f.read()
        # print(data)
        jsonData = json.loads(data)
    # print(jsonData)
    
    vlist = jsonData['data']['list']['vlist']
    mail = HTMLEmail("Test Title", "Test Description", vlist)
    html = mail.generate()
    # html = mail.vContents()
    
    # print(html)
    datestr = datetime.now().strftime("%Y%m%d%H%M%S")
    filename = working_dir + "html/" + datestr + ".html"
    with open(filename, "w") as f:
        f.write(html)
  
if __name__ == "__main__":
    main()
